
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: 8888483488
server:
 port: 8081



